// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyTGyCEgrFd9zvLjaEoa_gFsCNaKhzCjM',
    appId: '1:1012164637378:web:84e6a5ae3407afd3bcc15b',
    messagingSenderId: '1012164637378',
    projectId: 'portal-berita-6ec74',
    authDomain: 'portal-berita-6ec74.firebaseapp.com',
    databaseURL: 'https://portal-berita-6ec74-default-rtdb.firebaseio.com',
    storageBucket: 'portal-berita-6ec74.appspot.com',
    measurementId: 'G-99NFLKXYMX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyhdWJum1_zjoraxr6o6CcQusNpgDwoAU',
    appId: '1:1012164637378:android:ee8709b667dbb0f1bcc15b',
    messagingSenderId: '1012164637378',
    projectId: 'portal-berita-6ec74',
    databaseURL: 'https://portal-berita-6ec74-default-rtdb.firebaseio.com',
    storageBucket: 'portal-berita-6ec74.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqUq9Go0XBKfBbPkes_UlAinanvB63ruE',
    appId: '1:1012164637378:ios:a766d12250632dc3bcc15b',
    messagingSenderId: '1012164637378',
    projectId: 'portal-berita-6ec74',
    databaseURL: 'https://portal-berita-6ec74-default-rtdb.firebaseio.com',
    storageBucket: 'portal-berita-6ec74.appspot.com',
    iosBundleId: 'com.example.flutterNewsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqUq9Go0XBKfBbPkes_UlAinanvB63ruE',
    appId: '1:1012164637378:ios:476327180fd9fb07bcc15b',
    messagingSenderId: '1012164637378',
    projectId: 'portal-berita-6ec74',
    databaseURL: 'https://portal-berita-6ec74-default-rtdb.firebaseio.com',
    storageBucket: 'portal-berita-6ec74.appspot.com',
    iosBundleId: 'com.example.flutterNewsApp.RunnerTests',
  );
}
